name: Go Test
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: go get -t -v ./...
    - name: Test Code
      run: |
        docker login -u ${{ secrets.DOCKER_GITHUB_USERNAME }} -p ${{ secrets.DOCKER_GITHUB_TOKEN }} docker.pkg.github.com
        go test -race -coverprofile=coverage.txt -covermode=atomic ./...
    - uses: codecov/codecov-action@v1
      with:
        file: ./coverage.txt
